/**
 * This file was automatically generated by the Mule Cloud Connector Development Kit
 */
package org.mule.module.hbase;

import static org.junit.Assert.*;
import static org.mockito.Matchers.*;
import static org.mockito.Mockito.*;

import org.apache.hadoop.hbase.client.Result;
import org.junit.Before;
import org.junit.Test;
import org.mule.module.hbase.api.HBaseService;

public class HbaseTestCase
{
    private static final String SOME_ROW_KEY = "some-row-key";
    private static final String TABLE_NAME = "table-name";
    private HbaseCloudConnector connector;
    private HBaseService facade;

    @Before
    public void before() {
        connector = new HbaseCloudConnector();
        facade = mock(HBaseService.class);
        connector.setFacade(facade);
    }
    
    @Test
    public void testAlive()
    {
        when(facade.alive()).thenReturn(false);
        assertFalse(connector.alive());
        verify(facade).alive();
        
        reset(facade);
        when(facade.alive()).thenReturn(true);
        assertTrue(connector.alive());
        verify(facade).alive();
    }
    
    @Test
    public void testTableAdmin()
    {
        assertFalse(connector.existsTable(TABLE_NAME));
        verify(facade).existsTable(eq(TABLE_NAME));
        
        connector.createTable(TABLE_NAME);
        verify(facade).createTable(eq(TABLE_NAME));
        
        connector.deleteTable(TABLE_NAME);
        verify(facade).deleteTable(eq(TABLE_NAME));
        
        connector.isEnabledTable(TABLE_NAME);
        verify(facade).isDisabledTable(eq(TABLE_NAME));
        
        connector.enableTable(TABLE_NAME);
        verify(facade).enableTable(eq(TABLE_NAME));
        
        connector.disableTable(TABLE_NAME);
        verify(facade).disabeTable(eq(TABLE_NAME));
    }
    
    @Test
    public void testGetByRow()
    {
        Result mockResult = mock(Result.class);
        when(mockResult.isEmpty()).thenReturn(false);
        when(facade.get(eq(TABLE_NAME), eq(SOME_ROW_KEY))).thenReturn(mockResult);
        
        Result result = connector.get(TABLE_NAME, SOME_ROW_KEY);
        assertFalse(result.isEmpty());
    }
}
